### ISSUE TITLE
Docker 19.03 issue

### ISSUE THREAD

**Issue by lmtani** [broadinstitute/wdl-ide#5]
Hi!

Thank you for this work. It really helps writing good WDL workflows.

I think you docker-compose needs an update, adding an environment variable to disable TLS validation as [described here](https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/).

I'm using with VScode and works fine. Wishing for auto-complete for ease access to task outputs.

**Comment by dinvlad** [comment]
Thanks @lmtani, glad to hear it's helpful! I'll take a look at the TLS issue sometime soon.

Re auto-complete I'd like to implement that too, but not sure how to best approach this yet. I've created #6 to track this (no promises yet).
